name: Fineract VFD Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: kamiazya/setup-graphviz@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Login to Github Packages Docker
        uses: azure/docker-login@v1
        with:
          login-server: 'docker.pkg.github.com'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_AMETA_PROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_AMETA_PROD_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build with Gradle 1/2
        run: ./gradlew clean bootJar

      - name: Build with Gradle 2/2
        run: ./gradlew bootJar docker dockerPush -q -x rat -x compileTestJava -x test

      - name: tag, and push image to Amazon ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fineract-vfd
          IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}
