name: Build Ameta Dev
on:
  # workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - ameta
jobs:
  # Version Package
  build-server-images:
    name: Build Server Images
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Set Slug

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_AMETA_PROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_AMETA_PROD_SECRET_KEY }}
          aws-region: eu-west-2
          
      - name: change exec
        run: chmod +x ./gradlew
          
      - name: Build with Gradle 1/2
        run: ./gradlew clean bootJar

      - name: Build with Gradle 2/2
        run: ./gradlew bootJar docker dockerPush -q -x rat -x compileTestJava -x test
